#!/usr/bin/env bash

set -o nounset

main() {
    local csv_files=$(find $MASTER_DATA_DIRECTORY/../../ -name *.csv)
    local sorted_files_by_date=$(ls -tr $csv_files)
    gplogfilter $@ $sorted_files_by_date
}

main $@
