#!/usr/bin/env python

import sys
import os
import re


def process_file(file_path):
    file = None
    
    try:
        file = open(file_path, 'r')
        
    except:
        print("file does not exist: {file_path}".format(file_path=file_path))
        exit(1)

    current_beginning = ""
    
    for line in file.readlines():
        match = re.match(r'\d+-\d+-\d+.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*,.*', line)
        
        if match != None:
            current_beginning = match.group(0)

        line_to_print = line
        
        if match == None:
            line_to_print = "{current_beginning},{line}".format(current_beginning=current_beginning, line=line)

        sys.stdout.write(line_to_print)
    

def main():
    file_paths = sys.argv[1:]

    for file_path in file_paths:
        process_file(file_path)


if __name__ == "__main__":
   main()
